---
- name: Netzwerk Plugin installieren
  hosts: kubemaster
  become: true
  become_method: sudo
  tasks:

    - name: Calico installieren
      command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
      register: calico_output

    - name: Ausgabe anzeigen
      debug:
        var: calico_output.stdout_lines

    - name: Pause um Pods starten zu lassen
      pause:
        minutes: 4

    - name: Pods anzeigen
      command: kubectl get pods -n kube-system
      register: pods_output

    - name: Ausgabe anzeigen
      debug:
        var: pods_output.stdout_lines

    - name: Nodes anzeigen
      command: kubectl get nodes
      register: nodes_output

    - name: Ausgabe anzeigen
      debug:
        var: nodes_output.stdout_lines

