---
- name: Kubernetes Cluster konfigurieren
  hosts: kubemaster
  become: true
  become_method: sudo
  tasks:

    - name: Verzeichnis .kube erstellen
      file:
        path: $HOME/.kube
        state: directory

    - name: Kubeconfig zum Home Verzeichnis des Users kopieren
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0600

    - name: Netzwerk Plugin Calico installieren
      command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
