---
- name: Kubernetes Cluster konfigurieren
  hosts: kubemaster
  become: true
  tasks:

    - name: Kubernetes auf dem Master konfigurieren
      command: "{{ item }}"
      loop:
        - mkdir -p $HOME/.kube
        - sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        - sudo chown $(id -u):$(id -g) $HOME/.kube/config

    - name: Kubeconfig verifizieren
      command: kubectl get po -n kube-system
      register: kubectl_output

    - name: Ausgabe anzeigen
      debug:
        var: kubectl_output.stdout_lines

    - name: Kubeconfig zum Home Verzeichnis des Users kopieren
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_user }}/.kube/config
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0600

    - name: Netzwerk Plugin Calico installieren
      command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
