---
- name: Minikube Setup
  hosts: kubemaster
  become: true
  tasks:
  - name: Minikube Abhängigkeiten installieren
    apt:
      name:
        - curl
        - apt-transport-https
        - virtualbox
    tags:
      - minikube

  - name: Minikube herunterladen
    get_url:
      url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      dest: /usr/local/bin/minikube
      mode: '0755'
    tags:
      - minikube

  - name: Minikube starten
    shell: minikube start --driver=docker --force
    tags:
      - minikube

  - name: Status Minikube abrufen
    shell: minikube status
    register: minikube_status
    tags:
      - minikube

  - debug:
      var: minikube_status.stdout
    tags:
      - minikube

  - name: Minikube GUI aktivieren
    shell: minikube addons enable dashboard
    tags:
      - minikube
