---
- name: Docker Setup
  hosts: kubemaster, kubeworker
  become: true
  become_method: sudo
  tasks:
    - name: Docker Abh채ngigkeiten installieren
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        update_cache: yes

    - name: Docker GPG Key hinzuf체gen
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Docker Repo hinzuf체gen
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: sudo apt update
      apt:
        update_cache: yes

    - name: Docker installieren
      apt:
        name: docker-ce
        state: latest

    - name: Benutzer zu Docker Group hinzuf체gen
      user:
        name: nathan
        groups: docker
        append: yes
