---
- name: Grundkonfiguration Master
  hosts: kubemaster
  become: true
  become_method: sudo
  tasks:
    - name: Hostname setzen
      command: hostnamectl set-hostname "kubemaster.ansible.local"

    - name: /etc/hosts Eintrag
      lineinfile:
        path: /etc/hosts
        line: 192.168.26.164  kubemaster.ansible.local kubemaster
        state: present

    - name: Swap deaktivieren
      command: swapoff -a

    - name: Swap Eintrag aus /etc/fstab entfernen
      lineinfile:
        dest: /etc/fstab
        regexp: swap
        state: absent

    - name: Kernel Module laden
      command: "sudo tee /etc/modules-load.d/containerd.conf <<EOF
    overlay
    br_netfilter
    EOF"

    - name: overlay prüfen
      command: modprobe overlay

    - name: br_netfilter prüfen
      command: modprobe br_netfilter

    - name: Kubernetes Kernel Parameter setzen
      command: "sudo tee /etc/sysctl.d/kubernetes.conf <<EOF
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    net.ipv4.ip_forward = 1
    EOF"

    - name: Änderungen neuladen
      command: sysctl --system


