---
- name: Grundkonfiguration Worker
  hosts: kubeworker
  become: true
  become_method: sudo
  tasks:
    - name: Hostname setzen
      command: hostnamectl set-hostname "kubeworker.ansible.local"

    - name: /etc/hosts Eintrag
      lineinfile:
        path: /etc/hosts
        line: 192.168.26.166  kubeworker.ansible.local kubeworker
        state: present

    - name: Swap deaktivieren
      command: swapoff -a

    - name: Swap Eintrag aus /etc/fstab entfernen
      lineinfile:
        dest: /etc/fstab
        regexp: swap
        state: absent

    - name: Kopiere Kernel Module
      copy:
        src: /home/nathan/abschlussprojekt_zli/playbooks/help_files/containerd.conf
        dest: /etc/modules-load.d/containerd.conf

    - name: overlay prüfen
      command: modprobe overlay

    - name: br_netfilter prüfen
      command: modprobe br_netfilter

    - name: Kubernetes Kernel Parameter setzen
      copy:
        src: /home/nathan/abschlussprojekt_zli/playbooks/help_files/kubernetes.conf
        dest: /etc/sysctl.d/kubernetes.conf

    - name: Änderungen neuladen
      command: sysctl --system
